
services:
  backend:
    container_name: backend
    build: 
      context: ./project/backend/src
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 80:80

  clothingdb:
    container_name: clothingdb
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - clothingdb:/data/db

volumes:
  clothingdb: